### PR TITLE
update to react v16

### PR DESCRIPTION
**Pull request by noreiller**
Hi, I added some new dependencies (prop-types, create-react-class and core-js) and run the codemod for the prop-types.

### CODE REVIEW

**Comment by tomkp** [comment]
Hi! thanks for this... I was looking at doing this sometime as well!

What do you think about using `extends Component` instead of `createClass`?

Thanks

**Comment by noreiller** [comment]
I wanted to, but I didn't change the code as I wanted to only update the dependency. 
This requires more changes, as this one: https://reactjs.org/docs/react-without-es6.html#declaring-default-props .

**Comment by tomkp** [comment]
Makes sense - it's probably better to do it over a couple of PRs... I'll try and see why the Travis build is failing and then merge this in.

Thanks

**Comment by noreiller** [comment]
For the CI error, it seems the travis config needs to be updated with `sudo: required`.

**Pull request merged**
